label.title=Aplicación con idiomas
label.lang="Idioma seleccionado: {0}"
label.user=Nombre de usuario {0}
label.welcome=Bienvenido {0}
label.balance=Tu saldo actual es {0}.
label.name=Nombre
label.language=Idioma
label.money=Cuánto dinero tienes?
label.submit=Enviar

lang.es_ES=Español
lang.es_MX=Español de México
lang.en_GB=Inglés
lang.fr_FR=Francés
lang.de_DE=Alemán
lang.jp_JP=Japonés

label.time=Fechas y horas en el mundo
label.timeMadrid=Hora en Madrid (personalizada)
label.timeParis=Fecha en París (corta)
label.timeMexico=Hora en Ciudad de México (media)
label.timeCairo=Fecha y hora en el Cairo (larga)
label.timeTokyo=Fecha y hora en Tokyo (completa)